vsphere-server = ""
vsphere-user = ""
vsphere-password = ""
winadmin-password = ""
vm-cpu-num = "2"
vm-mem-size = "6144"
vsphere-cluster = ""
vsphere-datacenter = ""
vsphere-folder = "Templates"
vsphere-datastore = "vsanDatastore"
vm-disk-size = "61440"
vsphere-network = ""
winrm_username = "Administrator"
vmtools_iso_path = "[vsanDatastore] ISO/VMware-tools-windows-12.1.iso"
content_library = ""

os_iso_path_2022 = "[vsanDatastore] ISO/SW_DVD9_Win_Server_STD_CORE_2022_2108.11_64Bit_English_DC_STD_MLF_X23-17134.ISO"
vm-name-2022 = "Win2022-Template-Base"